name: RunicQuotes
options:
  bundleIdPrefix: com.po4yka
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
  createIntermediateGroups: true
  generateEmptyDirectories: false
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  RunicQuotes:
    type: application
    platform: iOS
    sources:
      - path: RunicQuotes
        excludes:
          - "**/*.md"
    resources:
      - path: RunicQuotes/Resources/Assets.xcassets
      - path: RunicQuotes/Resources/Fonts
        buildPhase: resources
      - path: RunicQuotes/Resources/SeedData
        buildPhase: resources
      - path: RunicQuotes/Resources/LaunchScreen.storyboard
      - path: RunicQuotes/Resources/Localizations
        buildPhase: resources
    info:
      path: RunicQuotes/App/Info.plist
    entitlements:
      path: RunicQuotes/RunicQuotes.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.po4yka.runicquotes
        INFOPLIST_FILE: RunicQuotes/App/Info.plist
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: RunicQuotes/RunicQuotes.entitlements

  RunicQuotesWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: RunicQuotesWidget
        excludes:
          - "**/*.md"
      - path: RunicQuotes/Models
        excludes:
          - "**/*.md"
      - path: RunicQuotes/Data
        excludes:
          - "**/*.md"
      - path: RunicQuotes/Utilities
        excludes:
          - "**/*.md"
    resources:
      - path: RunicQuotes/Resources/Fonts
        buildPhase: resources
      - path: RunicQuotes/Resources/SeedData
        buildPhase: resources
    info:
      path: RunicQuotesWidget/Info.plist
    entitlements:
      path: RunicQuotesWidget/RunicQuotesWidget.entitlements
    dependencies:
      - target: RunicQuotes
        embed: false
        link: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.po4yka.runicquotes.widget
        INFOPLIST_FILE: RunicQuotesWidget/Info.plist
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_ENTITLEMENTS: RunicQuotesWidget/RunicQuotesWidget.entitlements
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../../Frameworks"

  RunicQuotesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RunicQuotesTests
        excludes:
          - "**/*.md"
          - "**/Info.plist"
    dependencies:
      - target: RunicQuotes
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.po4yka.runicquotes.tests
        GENERATE_INFOPLIST_FILE: true

  RunicQuotesUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: RunicQuotesUITests
        excludes:
          - "**/*.md"
          - "**/Info.plist"
    dependencies:
      - target: RunicQuotes
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.po4yka.runicquotes.uitests
        GENERATE_INFOPLIST_FILE: true

  RunicQuotesWidgetTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RunicQuotesWidgetTests
        excludes:
          - "**/*.md"
          - "**/Info.plist"
    dependencies:
      - target: RunicQuotesWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.po4yka.runicquotes.widgettests
        GENERATE_INFOPLIST_FILE: true

schemes:
  RunicQuotes:
    build:
      targets:
        RunicQuotes: all
        RunicQuotesWidget: all
        RunicQuotesTests: [test]
        RunicQuotesUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - RunicQuotesTests
        - RunicQuotesUITests
    profile:
      config: Release
    archive:
      config: Release
