//
//  OldNorseGrammarContractTests.swift
//  RunicQuotes
//
//  Created by Claude on 09.10.26.
//

@testable import RunicQuotes
import XCTest

final class OldNorseGrammarContractTests: XCTestCase {
    private let service = HistoricalTranslationService()

    func testFiniteCopulaAgreesWithSubjectPersonNumberAndTense() {
        let examples = [
            ("I am", "ek em"), ("You are", "þú ert"), ("He is", "hann er"),
            ("We are", "vér erum"), ("You all are", "þér eruð"), ("They are", "þeir eru"),
            ("I was", "ek var"), ("You were", "þú vart"), ("We were", "vér várum"),
            ("They were", "þeir váru"),
        ]
        for (input, expected) in examples {
            let result = self.service.translate(text: input, script: .younger)
            XCTAssertEqual(result.normalizedForm, expected, input)
            XCTAssertEqual(result.supportLevel, .supported, input)
            XCTAssertEqual(result.evidenceTier, .reconstructed, input)
        }
    }

    func testTransitiveVerbGovernsAccusativeAndAdjectiveAgreement() {
        // Barnes NION I §§3.3,3.6,3.9.7.1, not values generated by the engine.
        let examples = [
            ("He has a wolf", "hann hefir úlf"), ("He had a wolf", "hann hafði úlf"),
            ("I have a wolf", "ek hefi úlf"), ("We have a wolf", "vér hǫfum úlf"),
            ("I hunt a great wolf", "ek veiði mikinn úlf"),
            ("He hunts a wolf", "hann veiðir úlf"), ("He hunted a wolf", "hann veiddi úlf"),
            ("Wolves hunt a wolf", "úlfar veiða úlf"), ("The wolves hunt", "úlfarnir veiða"),
        ]
        for (input, expected) in examples {
            let result = self.service.translate(text: input, script: .younger)
            XCTAssertEqual(result.normalizedForm, expected, input)
            XCTAssertEqual(result.supportLevel, .supported, input)
            XCTAssertTrue(result.provenance.contains { $0.sourceID == "barnes_nion" }, input)
        }
        XCTAssertEqual(self.service.translate(text: "He has a wolf", script: .younger).glyphOutput, "ᚼᛅᚾ ᚼᛁᚠᛁᚱ ᚢᛚᚠ")
    }

    func testGovernedPrepositionsApplyLocationDirectionAndAssociationCases() {
        let examples = [
            ("He is in a great mountain", "hann er í miklu fjalli"),
            ("She is with a great wolf", "hon er með miklum úlfi"),
            ("He hunts into a great mountain", "hann veiðir í mikit fjall"),
            ("She is great", "hon er mikil"), ("It is great", "þat er mikit"),
        ]
        for (input, expected) in examples {
            let result = self.service.translate(text: input, script: .younger)
            XCTAssertEqual(result.normalizedForm, expected, input)
            XCTAssertEqual(result.supportLevel, .supported, input)
        }
    }

    func testUnsupportedGrammarRetainsVisibleApproximationWithExplicitWarning() {
        for input in ["I am great", "He has", "He is. A wolf", "He is a wolf and a king", "He is with in a wolf"] {
            let result = self.service.translate(text: input, script: .younger, fidelity: .readable)
            XCTAssertTrue(result.isAvailable, input)
            XCTAssertEqual(result.supportLevel, .partial, input)
            XCTAssertEqual(result.evidenceTier, .approximate, input)
            XCTAssertFalse(result.userFacingWarnings.isEmpty, input)
        }
    }

    func testExplicitPluralFormsPreserveMutationInsteadOfGuessingSuffixes() {
        let result = self.service.translate(text: "mountains", script: .younger)
        XCTAssertEqual(result.normalizedForm, "fjǫll")
        XCTAssertEqual(result.glyphOutput, "ᚠᛁᚢᛚ")
        XCTAssertEqual(result.supportLevel, .supported)
    }

    func testInitialFiniteAgreementSurvivesUnsupportedLaterClausesWithoutCrossCase() {
        for input in ["He has a wolf and hunts", "He has a wolf. He hunts"] {
            let result = self.service.translate(text: input, script: .younger, fidelity: .readable)
            XCTAssertEqual(result.supportLevel, .partial)
            XCTAssertEqual(result.evidenceTier, .approximate)
            XCTAssertTrue(result.tokenBreakdown.contains { $0.sourceToken == "has" && $0.normalizedToken == "hefir" })
            XCTAssertTrue(result.tokenBreakdown.contains { $0.sourceToken == "wolf" && $0.normalizedToken == "úlfr" })
            XCTAssertFalse(result.userFacingWarnings.isEmpty)
        }
    }

}
